
USE Roman_g12_t
GO

CREATE TABLE USUARIO (
IdUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR(90) NOT NULL,
email VARCHAR(256) UNIQUE NOT NULL,
senha VARCHAR(25) NOT NULL
)
GO

CREATE TABLE TEMA (
idTema TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTema VARCHAR(80) UNIQUE NOT NULL
)
GO

CREATE TABLE PROJETO (
idProjeto INT PRIMARY KEY IDENTITY (1,1),
idTema TINYINT FOREIGN KEY REFERENCES TEMA(idTema),
idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
nome VARCHAR(80) NOT NULL,
descricao VARCHAR(500) NOT NULL
)
